version: "3.8"

services:
  mysql:
    build: .
    image: mysql:latest
    container_name: worpik_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Worpik123$
      MYSQL_DATABASE: worpik_db
      MYSQL_USER: manzana
      MYSQL_PASSWORD: Xperia1631$
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: